name: C++ CI with Qt

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt5
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2' # 选择你需要的Qt版本
        modules: 'qtbase' # qtbase通常包含Core和Widgets
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Run CMake
      run: cmake ./src -Bbuild
    - name: Build
      run: cmake -B build -S src
